version: '3.9'

services:
  kong-database:
    image: postgres:9.6
    container_name: kong-postgres
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  kong-migration:
    image: kong:3.5.0
    container_name: kong-migration
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
    command: kong migrations bootstrap

  kong:
    image: kong:3.5.0
    container_name: kong
    restart: always
    depends_on:
      kong-database:
        condition: service_healthy
      kong-migration:
        condition: service_started
    links:
      - kong-database:kong-database
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ROUTER_FLAVOR=radix
      - KONG_NGINX_WORKER_PROCESSES=1
      - KONG_PROXY_ACCESS_LOG=off
      - KONG_ANONYMOUS_REPORTS=off
#      - KONG_NGINX_EVENTS_WORKER_CONNECTIONS
#      - KONG_NGINX_MAIN_WORKER_RLIMIT_NOFILE
    user: root
    volumes:
      - "./src/kong/router/init.lua:/usr/local/share/lua/5.1/kong/router/init.lua"
      - "./src/kong/router/radix.lua:/usr/local/share/lua/5.1/kong/router/radix.lua"
      - "./src/kong/conf_loader/init.lua:/usr/local/share/lua/5.1/kong/conf_loader/init.lua"
      - "./kong.yaml:/kong.yaml"
    command: >
      bash -c "luarocks install radix-router && kong config db_import /kong.yaml && kong start"
